version: '3.8'
services:
  mypet:
    build:
      context: .  # 현재 디렉토리에서 빌드
      dockerfile: Dockerfile  # Dockerfile 지정
    image: mypet:latest  # 빌드된 이미지 이름
    container_name: mypet-container
    ports:
      - "8081:8080"  # 로컬 8081 -> 컨테이너 8080 포트 매핑
    env_file: 
      - .env  # 환경 변수 값을 .env 파일에서 로드
    networks:
      - mypet-network
    volumes:
      - ./application.properties:/app/config/application.properties  # 호스트의 파일을 컨테이너에 마운트
      - ./uploads:/path/to/upload/directory  # 업로드 디렉터리 마운트

  db:
    image: mysql:8.0  # MySQL 버전
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rpass  # 루트 비밀번호
      MYSQL_DATABASE: fpjt  # 초기 생성 데이터베이스
    ports:
      - "3307:3306"  # 로컬 3307 -> 컨테이너 3306 포트 매핑
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql  # 데이터 영구 저장용 볼륨
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - mypet-network

networks:
  mypet-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
