pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'mypet:latest'  // Docker 이미지 이름 설정
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/sunghyun-github/WithPet.git'
            }
        }
        stage('Build') {
            steps {
                dir('mypet') {
                    bat './gradlew build'  // Gradle 빌드 실행
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('mypet') {
                    bat 'docker-compose build'  // Docker Compose 빌드
                }
            }
        }
        stage('Docker Deploy') {
            steps {
                dir('mypet') {
                    bat 'docker-compose down'  // 기존 컨테이너 중지
                    bat 'docker-compose up -d'  // 새로운 컨테이너 배포
                }
            }
        }
    }
}
