pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'myapp:latest'
        SPRING_DATASOURCE_URL = 'jdbc:mysql://localhost:3306/fpjt?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8'
        SPRING_DATASOURCE_USERNAME = 'root'  
        SPRING_DATASOURCE_PASSWORD = 'rpass' 
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/sunghyun-github/WithPet.git'
            }
        }
        stage('Build') {
            steps {
                dir('mypet') {  // 'mypet' 폴더로 이동
                    bat './gradlew.bat build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('mypet') {  // 'mypet' 폴더로 이동
                    bat './gradlew.bat test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('mypet') {  // 'mypet' 폴더로 이동
                    bat 'docker build -t %DOCKER_IMAGE% .'
                }
            }
        }
        stage('Docker Deploy') {
            steps {
                dir('mypet') {  // 'mypet' 폴더로 이동
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}
